### ISSUE TITLE
Add an example of the compact wire encoding

### ISSUE THREAD

**Issue by boucadair** [tireddy2/DNS-resolver-information#14]
{"qnameminimization":true,"extendeddnserror":[15,16,17],"resinfourl":"https://resolver.example.com/guide"}

Follow the convention in https://www.rfc-editor.org/rfc/rfc8792.html#name-header in the draft, as appropriate

**Comment by tireddy2** [comment]
I don't see the need for compact wire encoding, fragmentation is not an issue with encrypted DNS.

**Comment by boucadair** [comment]
The comment does not apply anymore as we abandoned JSON. The initial comment was to make sure that we are using minified JSON

**Comment by tireddy2** [comment]
Got it, closing this issue.
